name: Backend AKS Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login --name myreactdotnetacr

    - name: Build Docker Image
      run: |
        docker build -t myreactdotnetacr.azurecr.io/dotnet_repo:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push myreactdotnetacr.azurecr.io/dotnet_repo:${{ github.sha }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v4
      with:
        resource-group: virtualmachine1
        cluster-name: myAKSCluster

    - name: Update Kubernetes Deployment Image
      run: |
        kubectl set image deployment/dotnet-api-deployment \
        dotnet-api-container=myreactdotnetacr.azurecr.io/dotnet_repo:${{ github.sha }}

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/dotnet-api-deployment