name: Docker ACR ACI Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        docker login myreactdotnetacr.azurecr.io \
        -u ${{ secrets.ACR_USERNAME }} \
        -p ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t myreactdotnetacr.azurecr.io/dotnet_api:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push myreactdotnetacr.azurecr.io/dotnet_api:${{ github.sha }}

    - name: Delete Existing ACI
      run: |
        az container delete \
          --resource-group virtualmachine1 \
          --name dotnet-api-container \
          --yes || true

    - name: Deploy to ACI
      run: |
        az container create \
          --resource-group virtualmachine1 \
          --name dotnet-api-container \
          --image myreactdotnetacr.azurecr.io/dotnet_api:${{ github.sha }} \
          --registry-login-server myreactdotnetacr.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label rakshitha-dotnet-api-123 \
          --ports 5000 \
          --os-type Linux \
          --cpu 1 \
          --memory 1.5